# This is a configuration file for powermeter app. 
#
# In this config file it is defined:
#  I2C addresses of four RPi Expander chips 
#  refresh rate
#  diode correction factors
#  resistor values
#

defaults:
  refresh rate: 5  # [Hz]


diode ports:
  diodeport 1:
      i2c address:
        adc: 0x48
        tca: 0x38

  diodeport 2:
      i2c address:
        adc: 0x49
        tca: 0x39

  diodeport 3:
      i2c address:
        adc: 0x4a
        tca: 0x3a

  diodeport 4:
      i2c address:
        adc: 0x4b
        tca: 0x3b

diodes:
  d0.0:
    name: 'ps100-6bb'
    resistor: '0'
    correction: 1

  d0.8:
    name: 'PS100-7'
    resistor: '2K'
    correction: 1

  d0.5:
    name: 'PS100-6b'
    resistor: '1K'
    correction: 1

  d1.2:
    name: 'PS100-7'
    resistor: '3K'
    correction: 1

  d1.0:
    name: 'SD445'
    resistor: '2.4K'
    correction: 1

  d1.4:
    name: 'RD100'
    resistor: '3.9K'
    correction: 1  

  d1.6:
    name: 'FDS10x10'
    resisto: '4.7K'
    correction: 1

  # the list goes on

# resistors used in amplification circuit

resistors:
  '0': 1000
  '1': 3000
  '2': 10000
  '3': 50000
  '4': 200000
  '5': 1000000
  '6': 5000000
  '7': 20000000

